{% set name = "kornia" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kornia-{{ version }}.tar.gz
  sha256: f834ccd51188d071ed286a6727471c94344ea2a718903cc6f0e56a92f9c66ac5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - pytest-runner
  run:
    - python >=3.7
    - pytorch >=1.10
    - packaging

test:
  imports:
    - kornia
    - kornia.augmentation
    - kornia.color
    - kornia.contrib
    - kornia.feature
    - kornia.filters
    - kornia.geometry
    - kornia.losses
    - kornia.utils

about:
  home: https://github.com/kornia/kornia
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Kornia is a differentiable computer vision library for PyTorch.
  doc_url: https://pypi.org/project/kornia/
  dev_url: https://github.com/kornia/kornia

extra:
  recipe-maintainers:
    - mxr-conda
    - dsangillo
    - benjaminrwilson
    - bubblyorca
    - mukhery
